name: quizapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Firebase packages
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9  # Firebase Firestore eklendi
  
  google_sign_in: ^6.3.0
  google_sign_in_ios: ^5.9.0
  google_sign_in_web: ^0.12.4+4
  
  
  # Supabase packages
  supabase_flutter: ^2.9.0
  
  # Local storage
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.1  
  shared_preferences: ^2.5.3
  
  # UI packages
  provider: ^6.1.5
  intl: ^0.19.0
  
  # Webview uyumlu sürüm (github_sign_in ile)
  webview_flutter: ^4.13.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
