// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4entp2IoUz7dJlLYuAsr2Wt4PiXvbu0',
    appId: '1:730242827890:web:dbb9fef15e5b60f26624eb',
    messagingSenderId: '730242827890',
    projectId: 'quizapp-af494',
    authDomain: 'quizapp-af494.firebaseapp.com',
    storageBucket: 'quizapp-af494.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCORW2hPOWSIMhA9v4rYK1v_qgxXaIS0Qo',
    appId: '1:730242827890:android:4f59f57ecbb664436624eb',
    messagingSenderId: '730242827890',
    projectId: 'quizapp-af494',
    storageBucket: 'quizapp-af494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQxKZ2Ns0HD9suAVL9nOBC0rQlK-kEGg',
    appId: '1:730242827890:ios:59ed2aa1d28c0e796624eb',
    messagingSenderId: '730242827890',
    projectId: 'quizapp-af494',
    storageBucket: 'quizapp-af494.firebasestorage.app',
    iosClientId:
        '730242827890-kskg491lqc7d2hvkiromsstskh8kv0u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQQxKZ2Ns0HD9suAVL9nOBC0rQlK-kEGg',
    appId: '1:730242827890:ios:59ed2aa1d28c0e796624eb',
    messagingSenderId: '730242827890',
    projectId: 'quizapp-af494',
    storageBucket: 'quizapp-af494.firebasestorage.app',
    iosClientId:
        '730242827890-kskg491lqc7d2hvkiromsstskh8kv0u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG4entp2IoUz7dJlLYuAsr2Wt4PiXvbu0',
    appId: '1:730242827890:web:7e6151abe57eba1b6624eb',
    messagingSenderId: '730242827890',
    projectId: 'quizapp-af494',
    authDomain: 'quizapp-af494.firebaseapp.com',
    storageBucket: 'quizapp-af494.firebasestorage.app',
  );
}
